services:
  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: -config.file=/etc/loki/config.yml
    volumes:
      - /home/ubuntu/monitoring/loki-config.yml:/etc/loki/config.yml:ro
      - /home/ubuntu/monitoring/loki-data:/loki
    ports:
      - "3100:3100"
    restart: always
    networks: [mynetwork]

  promtail:
    image: grafana/promtail:2.9.8
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /home/ubuntu/monitoring/promtail-config.yml:/etc/promtail/config.yml:ro
      - /home/ubuntu/logs:/var/log/app:ro
      - /var/log/redis:/var/log/redis:ro
      - /home/ubuntu/promtail/positions:/var/lib/promtail
    ports:
      - "9080:9080"
    restart: always
    networks: [mynetwork]

networks:
  mynetwork:
    driver: bridge