global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m
  external_labels:
    monitor: 'codelab-monitor'
  query_log_file: query_log_file.log
rule_files:
  - "prometheus-rule.yml"
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    honor_labels: false
    honor_timestamps: false
    scheme: 'http'
    static_configs:
      - targets: ['127.0.0.1:9090']
        labels:
          service: 'monitor-1'
  - job_name: 'node'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'spring-actuator-blue'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: [ 'app-blue:8080' ]
  - job_name: 'spring-actuator-green'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: [ 'app-green:8081' ]
#  - job_name: 'redis'
#    static_configs:
#      - targets: [ '${REMOTE_HOST}:9121']
#  - job_name: promtail
#    static_configs:
#      - targets: ["${REMOTE_HOST}:9080"]
