global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m
  external_labels:
    monitor: 'codelab-monitor'
  query_log_file: query_log_file.log
rule_files:
  - "prometheus-rule.yml"
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    honor_labels: false
    honor_timestamps: false
    scheme: 'http'
    static_configs:
      - targets: ['${REMOTE_HOST}:9090']
        labels:
          service: 'monitor-1'
  - job_name: 'node'
    static_configs:
      - targets: ['${REMOTE_HOST}:9090']